version: 1.1.2-{build}

clone_folder: c:\gopath\src\github.com\michaelsanford\bittray

stack: go 1.12

environment:
  GOPATH: c:\gopath
  CWD: c:\gopath\src\github.com\michaelsanford\bittray

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%CWD%;%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get

before_test:
  - go vet ./...

test_script:
  - go test -v ./...
  - go test -bench ./...

build_script:
  - go build

on_success:
  - ps: Invoke-RestMethod -Method Post -Uri "https://goreportcard.com/checks" -Body @{repo = "github.com/michaelsanford/bittray"}