version: 1.1.0-{build}

clone_folder: c:\gopath\src\github.com\michaelsanford\bittray

stack: go 1.11

environment:
  GOPATH: c:\gopath
  CWD: c:\gopath\src\github.com\michaelsanford\bittray

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%CWD%;%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get github.com/golang/lint/golint
  - go get

before_build:
  - go vet ./...
  - golint ./...

build_script:
  - go build
